/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.*;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class MainJFrame extends javax.swing.JFrame {   
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        try {
            data.read("dados.sav");
            //data.setDados();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(cadastraDialog, "ERRO de i/o - arquivo dados.sav not found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cadastraDialog = new javax.swing.JDialog();
        mainJPanel = new javax.swing.JPanel();
        loginJPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        userTextField = new javax.swing.JTextField();
        raTextField = new javax.swing.JTextField();
        passTextField = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userJPanel = new javax.swing.JPanel();
        userMainJPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        userCriarJPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        criarTicketTextArea = new javax.swing.JTextArea();
        userEnviarButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        userLerJPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lerTicketTextArea = new javax.swing.JTextArea();
        userEditarButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        userEnviarButton2 = new javax.swing.JButton();
        userDeletarButton = new javax.swing.JButton();
        userCancelarButton = new javax.swing.JButton();
        voltarButton1 = new javax.swing.JButton();
        userRespostaJPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lerTicketTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        voltarButton2 = new javax.swing.JButton();
        superUserJPanel = new javax.swing.JPanel();
        superUserMainJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        superUserExecutarButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        superUserResJPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lerTicketTextArea2 = new javax.swing.JTextArea();
        userEditarButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        userEnviarButton3 = new javax.swing.JButton();
        userCancelarButton1 = new javax.swing.JButton();
        voltarButton3 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        lerTicketTextArea4 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        AdminJPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        SairjButton = new javax.swing.JButton();

        javax.swing.GroupLayout cadastraDialogLayout = new javax.swing.GroupLayout(cadastraDialog.getContentPane());
        cadastraDialog.getContentPane().setLayout(cadastraDialogLayout);
        cadastraDialogLayout.setHorizontalGroup(
            cadastraDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        cadastraDialogLayout.setVerticalGroup(
            cadastraDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 200));
        setResizable(false);

        mainJPanel.setLayout(new java.awt.CardLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        raTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                raTextFieldKeyTyped(evt);
            }
        });

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        jLabel1.setText("Login");

        jLabel2.setText("Usuário");

        jLabel3.setText("R.A.");

        jLabel4.setText("Senha");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(login)
                        .addGap(18, 18, 18)
                        .addComponent(limpar))
                    .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(userTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addComponent(raTextField)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(limpar))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout loginJPanelLayout = new javax.swing.GroupLayout(loginJPanel);
        loginJPanel.setLayout(loginJPanelLayout);
        loginJPanelLayout.setHorizontalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        loginJPanelLayout.setVerticalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        mainJPanel.add(loginJPanel, "cardLogin");

        userJPanel.setPreferredSize(new java.awt.Dimension(772, 470));
        userJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                userJPanelComponentShown(evt);
            }
        });
        userJPanel.setLayout(new java.awt.CardLayout());

        userMainJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                userMainJPanelComponentShown(evt);
            }
        });

        jLabel6.setText("Menu");

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Criar Ticket");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ler Ticket aberto");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Ler resposta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jRadioButton1)
                .addGap(31, 31, 31)
                .addComponent(jRadioButton2)
                .addGap(31, 31, 31)
                .addComponent(jRadioButton3)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout userMainJPanelLayout = new javax.swing.GroupLayout(userMainJPanel);
        userMainJPanel.setLayout(userMainJPanelLayout);
        userMainJPanelLayout.setHorizontalGroup(
            userMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMainJPanelLayout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        userMainJPanelLayout.setVerticalGroup(
            userMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMainJPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 123, Short.MAX_VALUE))
        );

        userJPanel.add(userMainJPanel, "cardUserMain");

        userCriarJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                userCriarJPanelComponentShown(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        criarTicketTextArea.setColumns(20);
        criarTicketTextArea.setLineWrap(true);
        criarTicketTextArea.setRows(5);
        criarTicketTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(criarTicketTextArea);

        userEnviarButton1.setText("Enviar Ticket");
        userEnviarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEnviarButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Criar Ticket");

        jLabel10.setText("Descreva o seu problema:");

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(voltarButton)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(176, 176, 176)
                            .addComponent(userEnviarButton1))))
                .addGap(75, 75, 75))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(userEnviarButton1)
                .addGap(55, 55, 55)
                .addComponent(voltarButton))
        );

        javax.swing.GroupLayout userCriarJPanelLayout = new javax.swing.GroupLayout(userCriarJPanel);
        userCriarJPanel.setLayout(userCriarJPanelLayout);
        userCriarJPanelLayout.setHorizontalGroup(
            userCriarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCriarJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        userCriarJPanelLayout.setVerticalGroup(
            userCriarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCriarJPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        userJPanel.add(userCriarJPanel, "cardCriarTicket");

        userLerJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                userLerJPanelComponentShown(evt);
            }
        });

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        lerTicketTextArea.setEditable(false);
        lerTicketTextArea.setColumns(20);
        lerTicketTextArea.setLineWrap(true);
        lerTicketTextArea.setRows(5);
        lerTicketTextArea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(lerTicketTextArea);

        userEditarButton.setText("Editar");
        userEditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEditarButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Ticket aberto");

        userEnviarButton2.setText("Enviar");
        userEnviarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEnviarButton2ActionPerformed(evt);
            }
        });

        userDeletarButton.setText("Deletar");
        userDeletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDeletarButtonActionPerformed(evt);
            }
        });

        userCancelarButton.setText("Cancelar");
        userCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCancelarButtonActionPerformed(evt);
            }
        });

        voltarButton1.setText("Voltar");
        voltarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(voltarButton1)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(userEditarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userEnviarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userCancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userDeletarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userEditarButton)
                    .addComponent(userEnviarButton2)
                    .addComponent(userDeletarButton)
                    .addComponent(userCancelarButton))
                .addGap(55, 55, 55)
                .addComponent(voltarButton1))
        );

        javax.swing.GroupLayout userLerJPanelLayout = new javax.swing.GroupLayout(userLerJPanel);
        userLerJPanel.setLayout(userLerJPanelLayout);
        userLerJPanelLayout.setHorizontalGroup(
            userLerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLerJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        userLerJPanelLayout.setVerticalGroup(
            userLerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLerJPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        userJPanel.add(userLerJPanel, "cardLerTicket");

        userRespostaJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                userRespostaJPanelComponentShown(evt);
            }
        });

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        lerTicketTextArea1.setEditable(false);
        lerTicketTextArea1.setColumns(20);
        lerTicketTextArea1.setLineWrap(true);
        lerTicketTextArea1.setRows(5);
        lerTicketTextArea1.setWrapStyleWord(true);
        jScrollPane6.setViewportView(lerTicketTextArea1);

        jLabel12.setText("Resposta");

        voltarButton2.setText("Voltar");
        voltarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(voltarButton2)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(voltarButton2))
        );

        javax.swing.GroupLayout userRespostaJPanelLayout = new javax.swing.GroupLayout(userRespostaJPanel);
        userRespostaJPanel.setLayout(userRespostaJPanelLayout);
        userRespostaJPanelLayout.setHorizontalGroup(
            userRespostaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userRespostaJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        userRespostaJPanelLayout.setVerticalGroup(
            userRespostaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userRespostaJPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        userJPanel.add(userRespostaJPanel, "cardLerResposta");

        mainJPanel.add(userJPanel, "cardUser");

        superUserJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                superUserJPanelComponentShown(evt);
            }
        });
        superUserJPanel.setLayout(new java.awt.CardLayout());

        superUserExecutarButton.setText("Responder");
        superUserExecutarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superUserExecutarButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Selecione um usuário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superUserExecutarButton)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(superUserExecutarButton)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout superUserMainJPanelLayout = new javax.swing.GroupLayout(superUserMainJPanel);
        superUserMainJPanel.setLayout(superUserMainJPanelLayout);
        superUserMainJPanelLayout.setHorizontalGroup(
            superUserMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superUserMainJPanelLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        superUserMainJPanelLayout.setVerticalGroup(
            superUserMainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superUserMainJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        superUserJPanel.add(superUserMainJPanel, "SuperUserCard");

        superUserResJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                superUserResJPanelComponentShown(evt);
            }
        });

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        lerTicketTextArea2.setEditable(false);
        lerTicketTextArea2.setColumns(20);
        lerTicketTextArea2.setLineWrap(true);
        lerTicketTextArea2.setRows(5);
        lerTicketTextArea2.setWrapStyleWord(true);
        jScrollPane7.setViewportView(lerTicketTextArea2);

        userEditarButton1.setText("Editar");
        userEditarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEditarButton1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Ticket aberto");

        userEnviarButton3.setText("Enviar");
        userEnviarButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEnviarButton3ActionPerformed(evt);
            }
        });

        userCancelarButton1.setText("Cancelar");
        userCancelarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCancelarButton1ActionPerformed(evt);
            }
        });

        voltarButton3.setText("Voltar");
        voltarButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton3ActionPerformed(evt);
            }
        });

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        lerTicketTextArea4.setColumns(20);
        lerTicketTextArea4.setLineWrap(true);
        lerTicketTextArea4.setRows(5);
        lerTicketTextArea4.setWrapStyleWord(true);
        jScrollPane9.setViewportView(lerTicketTextArea4);

        jLabel18.setText("Resposta");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(voltarButton3)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(userEditarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userEnviarButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userCancelarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userEditarButton1)
                    .addComponent(userEnviarButton3)
                    .addComponent(userCancelarButton1))
                .addGap(18, 18, 18)
                .addComponent(voltarButton3))
        );

        javax.swing.GroupLayout superUserResJPanelLayout = new javax.swing.GroupLayout(superUserResJPanel);
        superUserResJPanel.setLayout(superUserResJPanelLayout);
        superUserResJPanelLayout.setHorizontalGroup(
            superUserResJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superUserResJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        superUserResJPanelLayout.setVerticalGroup(
            superUserResJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superUserResJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        superUserJPanel.add(superUserResJPanel, "superUserResponder");

        mainJPanel.add(superUserJPanel, "cardSuperMain");

        AdminJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                AdminJPanelComponentShown(evt);
            }
        });

        jLabel5.setText("Página do administrador (em construção)");

        javax.swing.GroupLayout AdminJPanelLayout = new javax.swing.GroupLayout(AdminJPanel);
        AdminJPanel.setLayout(AdminJPanelLayout);
        AdminJPanelLayout.setHorizontalGroup(
            AdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminJPanelLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel5)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        AdminJPanelLayout.setVerticalGroup(
            AdminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminJPanelLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel5)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        mainJPanel.add(AdminJPanel, "cardAdmin");

        SairjButton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        SairjButton.setText("Salvar e sair");
        SairjButton.setFocusable(false);
        SairjButton.setMaximumSize(new java.awt.Dimension(97, 21));
        SairjButton.setPreferredSize(new java.awt.Dimension(97, 21));
        SairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SairjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SairjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SairjButton.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String card = controleLogin.login(raTextField, userTextField, passTextField, 
                welcomeLabel);
        CardLayout layout = (CardLayout)mainJPanel.getLayout();
        layout.show(mainJPanel, card);
    }//GEN-LAST:event_loginActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        controle.limpa(userTextField);
        controle.limpa(raTextField);
        controle.limpa(passTextField);
    }//GEN-LAST:event_limparActionPerformed

    private void raTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_raTextFieldKeyTyped
        controle.apenasNum(evt);
    }//GEN-LAST:event_raTextFieldKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String card = controleUser.menu(jRadioButton1, jRadioButton2, jRadioButton3);
        CardLayout layout = (CardLayout)userJPanel.getLayout();
        layout.show(userJPanel, card);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userEnviarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEnviarButton1ActionPerformed
        controleUser.enviaTicket(criarTicketTextArea, userJPanel, cadastraDialog);
    }//GEN-LAST:event_userEnviarButton1ActionPerformed

    private void userEditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEditarButtonActionPerformed
        controleUser.editar(lerTicketTextArea, userEnviarButton2, userCancelarButton, 
                userEditarButton, voltarButton1, userDeletarButton);
    }//GEN-LAST:event_userEditarButtonActionPerformed

    private void userEnviarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEnviarButton2ActionPerformed
        controleUser.enviaTicket(lerTicketTextArea, userJPanel, cadastraDialog);
    }//GEN-LAST:event_userEnviarButton2ActionPerformed

    private void userDeletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDeletarButtonActionPerformed
        controleUser.deletaTicket(lerTicketTextArea, cadastraDialog, userJPanel);
    }//GEN-LAST:event_userDeletarButtonActionPerformed

    private void userLerJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userLerJPanelComponentShown
        controleUser.lerTicket(welcomeLabel, lerTicketTextArea, userEnviarButton2, 
                userCancelarButton, userEditarButton, userDeletarButton, voltarButton1);
    }//GEN-LAST:event_userLerJPanelComponentShown

    private void userCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCancelarButtonActionPerformed
        controleUser.cancela(lerTicketTextArea, userEnviarButton2, userCancelarButton,
                voltarButton1, userEditarButton, userDeletarButton);
    }//GEN-LAST:event_userCancelarButtonActionPerformed

    private void voltarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton1ActionPerformed
        CardLayout layout = (CardLayout)userJPanel.getLayout();
        layout.show(userJPanel, "cardUserMain"); 
    }//GEN-LAST:event_voltarButton1ActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        CardLayout layout = (CardLayout)userJPanel.getLayout();
        layout.show(userJPanel, "cardUserMain"); 
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void userCriarJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userCriarJPanelComponentShown
        welcomeLabel.setVisible(false);
        controleUser.verifica(criarTicketTextArea, jScrollPane4, jLabel10, userEnviarButton1);
    }//GEN-LAST:event_userCriarJPanelComponentShown

    private void userMainJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userMainJPanelComponentShown
        welcomeLabel.setVisible(true);
    }//GEN-LAST:event_userMainJPanelComponentShown

    private void userRespostaJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userRespostaJPanelComponentShown
        welcomeLabel.setVisible(false);
        controleUser.lerResposta(welcomeLabel, lerTicketTextArea1);
    }//GEN-LAST:event_userRespostaJPanelComponentShown

    private void voltarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton2ActionPerformed
        CardLayout layout = (CardLayout)userJPanel.getLayout();
        layout.show(userJPanel, "cardUserMain"); 
    }//GEN-LAST:event_voltarButton2ActionPerformed

    private void superUserExecutarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superUserExecutarButtonActionPerformed
        controleSuperUser.executar(jComboBox1);
        CardLayout layout = (CardLayout)superUserJPanel.getLayout();
        layout.show(superUserJPanel, "superUserResponder");
    }//GEN-LAST:event_superUserExecutarButtonActionPerformed

    private void userEditarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEditarButton1ActionPerformed
        controleSuperUser.editar(lerTicketTextArea4, userEnviarButton3, userCancelarButton1,
                userEditarButton1, voltarButton3);
    }//GEN-LAST:event_userEditarButton1ActionPerformed

    private void userEnviarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEnviarButton3ActionPerformed
        controleSuperUser.enviaResposta(lerTicketTextArea4, superUserJPanel, cadastraDialog);
    }//GEN-LAST:event_userEnviarButton3ActionPerformed

    private void userCancelarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCancelarButton1ActionPerformed
        controleSuperUser.cancela(lerTicketTextArea4, userEnviarButton3, userCancelarButton1,
                voltarButton3, userEditarButton1);
    }//GEN-LAST:event_userCancelarButton1ActionPerformed

    private void voltarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton3ActionPerformed
        CardLayout layout = (CardLayout)superUserJPanel.getLayout();
        layout.show(superUserJPanel, "SuperUserCard"); 
    }//GEN-LAST:event_voltarButton3ActionPerformed

    private void superUserJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_superUserJPanelComponentShown
        controleSuperUser.usuariosComTicket(jComboBox1);
        SairjButton.setVisible(true);
    }//GEN-LAST:event_superUserJPanelComponentShown

    private void superUserResJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_superUserResJPanelComponentShown
        controleSuperUser.ler(welcomeLabel, lerTicketTextArea2, lerTicketTextArea4, userEnviarButton3, 
                userCancelarButton1, userEditarButton1, voltarButton3);
    }//GEN-LAST:event_superUserResJPanelComponentShown

    private void SairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairjButtonActionPerformed
            try {
                data.save();
            } catch (IOException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            System.exit(0);
    }//GEN-LAST:event_SairjButtonActionPerformed

    private void AdminJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AdminJPanelComponentShown
        SairjButton.setVisible(true);
    }//GEN-LAST:event_AdminJPanelComponentShown

    private void userJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userJPanelComponentShown
        SairjButton.setVisible(true);
    }//GEN-LAST:event_userJPanelComponentShown

    Dados data = new Dados();
    LoginController controleLogin = new LoginController();
    UserController controleUser = new UserController();
    SuperUserController controleSuperUser = new SuperUserController();
    Controller controle = new Controller();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminJPanel;
    private javax.swing.JButton SairjButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog cadastraDialog;
    private javax.swing.JTextArea criarTicketTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea lerTicketTextArea;
    private javax.swing.JTextArea lerTicketTextArea1;
    private javax.swing.JTextArea lerTicketTextArea2;
    private javax.swing.JTextArea lerTicketTextArea4;
    private javax.swing.JButton limpar;
    private javax.swing.JButton login;
    private javax.swing.JPanel loginJPanel;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JTextField raTextField;
    private javax.swing.JButton superUserExecutarButton;
    private javax.swing.JPanel superUserJPanel;
    private javax.swing.JPanel superUserMainJPanel;
    private javax.swing.JPanel superUserResJPanel;
    private javax.swing.JButton userCancelarButton;
    private javax.swing.JButton userCancelarButton1;
    private javax.swing.JPanel userCriarJPanel;
    private javax.swing.JButton userDeletarButton;
    private javax.swing.JButton userEditarButton;
    private javax.swing.JButton userEditarButton1;
    private javax.swing.JButton userEnviarButton1;
    private javax.swing.JButton userEnviarButton2;
    private javax.swing.JButton userEnviarButton3;
    private javax.swing.JPanel userJPanel;
    private javax.swing.JPanel userLerJPanel;
    private javax.swing.JPanel userMainJPanel;
    private javax.swing.JPanel userRespostaJPanel;
    private javax.swing.JTextField userTextField;
    private javax.swing.JButton voltarButton;
    private javax.swing.JButton voltarButton1;
    private javax.swing.JButton voltarButton2;
    private javax.swing.JButton voltarButton3;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
